name: push image

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: docker-registry.ap12.net
  IMAGE_NAME: komaken-bot

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and push
        run: |
          docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
